// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJyGfrBYGlPuGd06rZuacodN__9QXykT0',
    appId: '1:1087904315481:web:d2f4357a5e52afe7301948',
    messagingSenderId: '1087904315481',
    projectId: 'payziff',
    authDomain: 'payziff.firebaseapp.com',
    storageBucket: 'payziff.appspot.com',
    measurementId: 'G-M0RJ09L0N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9h73ME2Noz5vYuu-BFlGJ8Z-vWW_Jy8Y',
    appId: '1:1087904315481:android:e57397fb1b46a4d2301948',
    messagingSenderId: '1087904315481',
    projectId: 'payziff',
    storageBucket: 'payziff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArmP-bgvgcuEVLW26AHlQ7B2a6xBCTEKg',
    appId: '1:1087904315481:ios:d23f8b986482b29b301948',
    messagingSenderId: '1087904315481',
    projectId: 'payziff',
    storageBucket: 'payziff.appspot.com',
    iosClientId: '1087904315481-mhua9fgbp1mtsr95kqa0mobd5e5r77tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArmP-bgvgcuEVLW26AHlQ7B2a6xBCTEKg',
    appId: '1:1087904315481:ios:d23f8b986482b29b301948',
    messagingSenderId: '1087904315481',
    projectId: 'payziff',
    storageBucket: 'payziff.appspot.com',
    iosClientId: '1087904315481-mhua9fgbp1mtsr95kqa0mobd5e5r77tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
